source 'https://rubygems.org'


ruby '2.1.5'
gem 'rails', '4.2.3'

gem 'sass-rails', '~> 5.0'

gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'

gem 'turbolinks'

gem 'jbuilder', '~> 2.0'

gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do

  gem 'sqlite3', '~> 1.3.10'
  gem 'pry', '~> 0.10.2'

end
group :production do
	gem 'pg', '~> 0.18.3'
	gem 'rails_12factor', '~> 0.0.3'
end


gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'bootstrap-sass', '~> 3.3.5'
